# @package _global_

defaults:
  - _self_
  # - data: uci_data # choose datamodule with `test_dataloader()` for evaluation
  - data: synthetic_data.yaml
  - model: Rmcl.yaml
  - logger: many_loggers.yaml
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # - experiment: setup.yaml
  # - experiment: mixtures_uni_to_gaussians.yaml
  # - experiment: uci/setup/uci_wine_setup.yaml
  - experiment: A_three_gaussians_changedist.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null