_target_: src.models.Rmcl.Rmcl

num_hypothesis: 20
restrict_to_square: True
hidden_layers: [256, 256]
input_dim: 1
output_dim: 2

hparams:
  # training loss params
  name: "rmcl"
  training_wta_mode: "wta"
  training_epsilon: 0.05
  training_conf_weight: 1.
  training_distance: "euclidean-squared"

  # optimization params
  optimizer: "Adam"
  learning_rate: 0.001

  ### eval args
  custom_eval_computation: False
  dist_type_eval: "euclidean"

  # h optimization params
  h_optimization: False
  h_min: 0.1
  h_max: 2
  limit_val_batches_h_opt: None
  batch_size_h_opt: 256
  h_tol: 0.1

  denormalize_predictions: False

  # Risk params
  compute_risk: True

  # MSE params
  compute_mse: True

  plot_mode: False
  plot_mode_training: False
  plot_training_frequency: 1

  temperature_ini: 1.0
  scheduler_mode: "linear"
  temperature_decay: 0.9

  temperature_lim: None
  wta_after_temperature_lim: False

  annealed_epsilon: False
  epsilon_ini: None
  epsilon_decay: None

  compute_risk_val: True
